server:
  port: 8080
  servlet:
    context-path: /api/v1/
  forward-headers-strategy: framework

spring:
  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rocketdan?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: rocketdan
    password: 1234

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 14b9986550f66f219600
            client-secret: 7a0dcbc61991969b507521491e2c32bf028e6697
            scope: user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE
        SQL: DEBUG

# JWT
jwt:
  accesskey: 1234
  refreshkey: 1234
  datakey: 1234
  expire:
    access: 300000
    refresh: 3600000
  secret: 1234

github:
  accessToken: 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

front_url: http://localhost:3000
